name: UnNetHack CI builds

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      run: "sudo dpkg --add-architecture i386 && dpkg --print-foreign-architectures && sudo apt-get update"

    - name: install dependencies
      run: sudo apt-get install gcc-mingw-w64-i686 wine-development wine32 wine-binfmt imagemagick

    - name: binfmt
      run: sudo update-binfmts --import /usr/share/binfmts/wine

    - name: build
      run: sys/autoconf/build_win32.sh

    - name: environment variables
      run: |
          echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT" >> $GITHUB_ENV
          echo "VERSION=$(grep VERSION_STRING include/date.h | cut -f 2 -d \")" >> $GITHUB_ENV

    - name: unnethack-win32-${VERSION}-${GITHUB_SHA_SHORT}.zip
      uses: actions/upload-artifact@v2
      with:
        path: /tmp/unnethack_win32/unnethack-win32-*.zip

    - name: unnethack-${VERSION}-${GITHUB_SHA_SHORT}.tar.gz
      uses: actions/upload-artifact@v2
      with:
        path: /tmp/unnethack_win32/unnethack-*.tar.gz


  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      env:
        CFLAGS: '-O2 -Wall -Wextra -fno-common -Werror=format -Werror=return-type -Werror=uninitialized -Werror=implicit-function-declaration -Wno-format-overflow'
        LFLAGS: '-fno-common'
      run: "./configure --with-owner=`id -un` --with-group=`id -gn` --enable-wizmode=`id -un` --enable-dummy-graphics --enable-lisp-graphics --enable-curses-graphics --disable-x11-graphics --enable-tty-graphics"

    - name: make
      run: make all

    - name: install libcheck
      run: sudo apt-get install check

    - name: make check
      run: make check

  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      env:
        CFLAGS: '-O2 -Wall -Wextra -fno-common -Werror=format -Werror=return-type -Werror=uninitialized -Werror=implicit-function-declaration -Wno-format-overflow'
        LFLAGS: '-fno-common'
      run: "./configure --with-owner=`id -un` --with-group=`id -gn` --enable-wizmode=`id -un` --enable-dummy-graphics --enable-lisp-graphics --enable-curses-graphics --disable-x11-graphics --enable-tty-graphics"

    - name: make
      run: make all
