name: UnNetHack CI builds

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: "sudo dpkg --add-architecture i386 && dpkg --print-foreign-architectures && sudo apt-get update"

    - name: install dependencies
      run: sudo apt-get install gcc-mingw-w64-i686 wine-stable wine32 wine-binfmt imagemagick

    - name: build
      run: sys/autoconf/build_win32.sh

  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      env:
        CFLAGS: '-O2 -Wall -Wextra -fno-common -Werror=format -Werror=return-type -Werror=uninitialized -Werror=implicit-function-declaration -Wno-format-overflow'
        LFLAGS: '-fno-common'
      run: "./configure --with-owner=`id -un` --with-group=`id -gn` --enable-wizmode=`id -un` --enable-dummy-graphics --enable-lisp-graphics --enable-curses-graphics --disable-x11-graphics --enable-tty-graphics"

    - name: make
      run: make all

    - name: install libcheck
      run: sudo apt-get install check

    - name: make check
      run: make check

  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      env:
        CFLAGS: '-O2 -Wall -Wextra -fno-common -Werror=format -Werror=return-type -Werror=uninitialized -Werror=implicit-function-declaration -Wno-format-overflow'
        LFLAGS: '-fno-common'
      run: "./configure --with-owner=`id -un` --with-group=`id -gn` --enable-wizmode=`id -un` --enable-dummy-graphics --enable-lisp-graphics --enable-curses-graphics --disable-x11-graphics --enable-tty-graphics"

    - name: make
      run: make all
